blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/Ewm8aTTJ3K
    about: Inquire for information or ask questions.
  - name: QQ群
    url: https://qm.qq.com/q/iBHAlpERh0
    about: 获取信息或询问问题。